# ProxMox Infrastructure Configuration
# Kanal Infrastructure Setup

cluster:
  name: "kanal-cluster"
  nodes:
    - name: "kanal-pve-01"
      ip: "192.168.1.10"
      role: "primary"
      hardware:
        cpu: "Intel i5-13420H (8C/12T)"
        memory: "32 GB DDR5-5600"
        storage: "1 TB NVMe PCIe 4.0"
        power: "180W"

network:
  management:
    subnet: "192.168.1.0/24"
    gateway: "192.168.1.1"
    dns: 
      - "8.8.8.8"
      - "8.8.4.4"
  
  vm_networks:
    - name: "vm-network"
      vlan: 100
      subnet: "10.0.100.0/24"
      gateway: "10.0.100.1"
    
    - name: "container-network"
      vlan: 200
      subnet: "10.0.200.0/24"
      gateway: "10.0.200.1"

storage:
  local:
    type: "directory"
    path: "/var/lib/vz"
    content: ["images", "vztmpl", "iso"]
    size: "512 GB NVMe SSD"

  # Storage allocation on 512GB NVMe SSD (no local backups)
  partitions:
    system: "80 GB"       # ProxMox system
    vm_storage: "400 GB"  # VM disk images (increased!)
    templates: "20 GB"    # ISO/templates
    swap: "12 GB"         # Reserved for swap
    # Total: 512 GB (no backup storage needed!)

  # External backup to Synology NAS
  nas_backup:
    type: "NFS/SMB"
    target: "Synology NAS"
    benefits:
      - "No local storage used for backups"
      - "More space available for VMs (400GB instead of 350GB)"
      - "Network-attached storage redundancy"
      - "Can keep longer retention (7+ days)"

backup:
  schedule: "daily"
  time: "02:00"
  retention: 7           # Back to 7 days (NAS has plenty space!)
  storage: "nas-backup"  # Synology NAS storage
  compression: "lzo"     # Still compress for faster transfer

  # NAS backup strategy
  nas_configuration:
    storage_id: "nas-backup"
    type: "nfs"           # or "cifs" for SMB
    server: "synology.local"  # Your NAS hostname/IP
    path: "/volume1/proxmox-backups"
    options: "vers=3"     # NFS version

  benefits:
    - "7 days retention (or more if desired)"
    - "No local storage impact"
    - "Redundant storage on NAS"
    - "Network backup allows for offsite copies"
    - "50GB extra space freed up for VMs"